### ISSUE TITLE
[Feature Request] Weapon/hand Location Offset and Scale Configs

### ISSUE THREAD

**Issue by Mr-Foxtrot** [whateverusername0/VRTRAKILL#140]
**Is your feature request related to a problem? Please describe.**
The rocket launcher is just, gigantic compared to the rest of the weapons. Same also sorta goes for the shotgun. Whenever I equip the rocket launcher it kinda blocks my vision. The position of the shotgun/rocket launcher also feel a lil off, but that's just probably preference and not a bug persay.

**Describe the solution you'd like**
An option to configure the scale/location of weapons on a per-weapon basis would be handy.

**Describe alternatives you've considered**
To my knowledge, there is VR software that can offset your tracked controllers, however this would apply to *everything*, not specific weapons so there still lies a problem.

**Comment by whateverusername0** [comment]
whenever i change weapons' scale it screws up their position which is literally unpredictable, making it impossible, sorry. and the rocket launcher is supposed to be huge by design 🤷‍♂️
reference: official 5-3 song cover
![image](https://github.com/whateverusername0/VRTRAKILL/assets/113782077/7d5a4485-8a9d-41e7-8121-3e023afca9ae)
