### ISSUE TITLE
Slow Movement on Index(maybe also in general)

### ISSUE THREAD

**Issue by Thesillygoofygooberfromyt** [whateverusername0/VRTRAKILL#42]
**Describe the bug**
Movement in any type of form seems slow or not powerful, dashing in the tutorial doesnt even reach you far enough to reach next tutorial. Wall bounces are literal shit and slam storage doesnt even get you higher than the gmod building u spawn next to with. 

**Steps to Reproduce**
1. Do this
2. Do that
3. See error

**Expected behavior**
Fast boiiiiiiiiiiiiiiiii

**Real behavior**
Slowness lvl 3 and mining fatigue

**Media**
I can send vid in dc server, my name is also Hyper there

**Other info:**
Index, on version 0.9

**Additional context**
Context

**Comment by whateverusername0** [comment]
the config. do not override movement values thingie. enable it.

**Comment by TacticalPan** [comment]
`"Do not override movement values": true ` does not fix this, am on index

**Comment by whateverusername0** [comment]
> and speed is still terrible
can't do anything about it, at least for now. i've made it the same as v2 speed. check if you're slower than v2

**Comment by TacticalPan** [comment]
> can't do anything about it, at least for now. i've made it the same as v2 speed. check if you're slower than v2

did some testing and its definitely related to the refresh rate of the headset, on 90hz its not an issue but on 144hz its extremely slow - a lot slower than v2
using ultratweaker to manually increase my speed by 2.2x to make it the same/similar to v2 works as a fix

**Comment by whateverusername0** [comment]
> on 90hz its not an issue but on 144hz its extremely slow

now **that's** the source of the constant movement issues.
that also explains why only *some* people have struggled w/ that. i personally play on 72hz and have never experienced any of the above, so i'm having troubles figuring out why does this occur.
unfortunately i can't do anything about it, because **the game** has it's movement processed in the Update() method, which is called **every** frame and is 200% not suitable for physics, so i'll leave a note somewhere to lower the headset refresh rate. 

lifesaver. my eternal gratitude upon thee.
