### ISSUE TITLE
Hand too big, cant get past tutorial bcus not letting me punch

### ISSUE THREAD

**Issue by BrayDoesStuffYT** [whateverusername0/VRTRAKILL#65]
**Describe the bug**
Hand is too big, doesnt let me punch. Also weird flashy glitch effect on hand. I think this is in common issues, but I dont believe ive ever turned on steamVR world size tweaked & I dunno how exactly to fix as google gives no results. I dont have my weapon position as middle, never have.

**Steps to Reproduce**
Load into a level, i guess

**Expected behavior**
Hand is normal

**Real behavior**
Hand is humongous & doesnt let me punch. all controls other than that work

**Media**
If applicable, add screenshots / videos to help explain your problem.

**Other info:**
 - Headset: [e.g. Oculus Quest 2
 - Intermediate software Steam VR
 - VRTRAKILL Version Latest

**Additional context**

**Comment by BrayDoesStuffYT** [comment]
As such I also cannot get past the tutorial first room since I cant punch the boards.

**Comment by whateverusername0** [comment]
Can you please send me more info about your problem, because right now it's simply "I can't punch my hand is amongus idk why pls help". Perhaps, a video or a screenshot.
I'm also gonna need bepinex logs (in game/bepinex folder) and unity logs (in AppData/LocalLow/Hakita/ULTRAKILL/Player(latest).log to check if nothing weird is happening over there, because most of the time the problem can be located via logs.

**Comment by whateverusername0** [comment]
it's been 2 weeks bruh. can't fix what i can't reproduce, srry
